# Generated by Django 3.0.5 on 2020-09-15 11:05

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import rota_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0029_userprofile_default_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_availability',
        ),
        migrations.CreateModel(
            name='DefaultAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', jsonfield.fields.JSONField(default=rota_app.models.default_availability)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_availability_business', to='rota_app.Business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_availability', to='rota_app.Employee')),
            ],
        ),
    ]
