# Generated by Django 3.0.5 on 2020-09-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0030_auto_20200915_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultavailability',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_availability', to='rota_app.Employee'),
        ),
    ]
