# Generated by Django 3.0.5 on 2020-09-17 17:28

from django.db import migrations
import jsonfield.fields
import rota_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0031_auto_20200915_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_availability',
            field=jsonfield.fields.JSONField(default=rota_app.models.default_availability),
        ),
        migrations.DeleteModel(
            name='DefaultAvailability',
        ),
    ]
