# Generated by Django 3.0.5 on 2020-09-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0032_auto_20200917_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
