# Generated by Django 3.0.5 on 2020-06-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pos_department', to='rota_app.Department'),
            preserve_default=False,
        ),
    ]
