# Generated by Django 3.0.5 on 2020-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0002_auto_20200409_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
