# Generated by Django 3.0.4 on 2020-04-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0003_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
