# Generated by Django 3.0.5 on 2020-06-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0003_auto_20200623_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_department', to='rota_app.Department'),
        ),
    ]
