# Generated by Django 3.0.5 on 2020-06-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0004_shift_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
