# Generated by Django 3.0.5 on 2020-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0005_remove_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
