# Generated by Django 3.0.4 on 2020-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0007_auto_20200406_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
    ]
