# Generated by Django 3.0.5 on 2020-07-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0008_auto_20200709_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
