# Generated by Django 3.0.5 on 2020-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0010_shiftswap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftswap',
            name='admin_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftswap',
            name='employee_approved',
            field=models.BooleanField(null=True),
        ),
    ]
