# Generated by Django 3.0.5 on 2020-07-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0011_auto_20200724_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
