# Generated by Django 3.0.5 on 2020-08-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0016_auto_20200820_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_business', to='rota_app.Business'),
        ),
    ]
