# Generated by Django 3.0.5 on 2020-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0018_department_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
