# Generated by Django 3.0.5 on 2020-08-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0021_auto_20200825_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_business', to='rota_app.Business'),
        ),
    ]
