# Generated by Django 3.0.5 on 2020-08-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0022_availability_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], default='F', max_length=1),
        ),
    ]
