# Generated by Django 3.0.5 on 2020-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0024_userprofile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='total_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
