# Generated by Django 3.0.5 on 2020-08-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0025_business_total_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='total_employees',
            field=models.IntegerField(default=10),
        ),
    ]
