# Generated by Django 3.0.5 on 2020-08-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0026_auto_20200830_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='subscription_cancellation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
