# Generated by Django 3.0.5 on 2020-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0027_business_subscription_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='total_employees',
            field=models.IntegerField(default=5),
        ),
    ]
