# Generated by Django 3.0.5 on 2020-09-17 17:30

from django.db import migrations
import jsonfield.fields
import rota_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0028_auto_20200910_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_availability',
            field=jsonfield.fields.JSONField(default=rota_app.models.default_availability),
        ),
    ]
