# Generated by Django 3.0.5 on 2020-10-02 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0030_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_site', to='rota_app.Site'),
        ),
    ]
