# Generated by Django 3.0.5 on 2020-12-30 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rota_app', '0032_employee_site_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='site_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
