# Generated by Django 3.0.5 on 2020-12-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0033_site_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='site_admin',
        ),
    ]
