# Generated by Django 3.0.5 on 2021-01-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0034_remove_employee_site_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='business',
        ),
        migrations.AddField(
            model_name='availability',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_site', to='rota_app.Site'),
        ),
    ]
