# Generated by Django 3.0.5 on 2021-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0037_auto_20210113_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='wage',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
