# Generated by Django 3.0.5 on 2021-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0039_shift_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='wage_type',
            field=models.CharField(choices=[('H', 'Hourly'), ('S', 'Salary'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
