# Generated by Django 3.0.5 on 2021-01-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0040_auto_20210124_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
