# Generated by Django 3.0.5 on 2021-01-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0041_shift_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='total_employees',
            field=models.IntegerField(default=15),
        ),
    ]
