# Generated by Django 3.0.5 on 2021-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0042_auto_20210131_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='plan',
            field=models.CharField(choices=[('F', 'Free'), ('T', 'Trial'), ('P', 'Premium')], default='F', max_length=1),
        ),
    ]
