# Generated by Django 3.0.5 on 2021-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0044_availability_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
