# Generated by Django 3.0.5 on 2021-02-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0045_availability_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_length',
            field=models.IntegerField(default=0),
        ),
    ]
