# Generated by Django 3.0.5 on 2021-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0046_shift_break_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='absent',
            field=models.CharField(choices=[('Authorised', 'Authorised'), ('Unauthorised', 'Unauthorised'), ('Compassionate', 'Compassionate'), ('Other', 'Other'), ('None', 'None')], default='N', max_length=14),
        ),
    ]
