# Generated by Django 3.0.5 on 2021-02-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0047_shift_absent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='absent',
            new_name='absence',
        ),
    ]
