# Generated by Django 3.0.5 on 2021-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0048_auto_20210209_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='absence',
            field=models.CharField(choices=[('Authorised', 'Authorised'), ('Unauthorised', 'Unauthorised'), ('Compassionate', 'Compassionate'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=14),
        ),
    ]
