# Generated by Django 3.0.5 on 2021-02-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0049_auto_20210210_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='absence_info',
            field=models.TextField(blank=True),
        ),
    ]
