# Generated by Django 3.0.5 on 2021-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0050_shift_absence_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='stage',
            field=models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished'), ('Approval', 'Approval'), ('Creation', 'Creation')], default='Unpublished', max_length=12),
        ),
        migrations.AddField(
            model_name='shift',
            name='wage_type',
            field=models.CharField(choices=[('H', 'Hourly'), ('S', 'Salary'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
