# Generated by Django 3.0.5 on 2021-02-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0051_auto_20210216_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_forecast', to='rota_app.Site')),
            ],
        ),
    ]
