# Generated by Django 3.0.5 on 2021-02-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0052_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_approval', models.BooleanField(default=False)),
                ('min_time', models.CharField(default='00:00', max_length=5)),
                ('max_time', models.CharField(default='23:45', max_length=5)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='rota_app.Business')),
            ],
        ),
    ]
