# Generated by Django 3.0.5 on 2021-02-17 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0053_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='min_time',
        ),
        migrations.AlterField(
            model_name='settings',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rota_app.Business'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.CharField(default='00:00', max_length=5)),
                ('max_time', models.CharField(default='23:45', max_length=5)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rota_app.Site')),
            ],
        ),
    ]
