# Generated by Django 3.0.5 on 2021-02-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0055_auto_20210218_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_department', to='rota_app.Department'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='rota_app.Employee'),
        ),
    ]
