# Generated by Django 3.0.5 on 2021-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0056_auto_20210218_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='open_shift',
            field=models.BooleanField(default=False),
        ),
    ]
