# Generated by Django 3.0.5 on 2021-03-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0057_shift_open_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='business',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site',
        ),
    ]
