# Generated by Django 3.0.5 on 2021-03-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0058_auto_20210307_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='business',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rota_app.Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rota_app.Site'),
            preserve_default=False,
        ),
    ]
