# Generated by Django 3.0.5 on 2021-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0060_auto_20210308_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='time_increment',
            field=models.IntegerField(default=15),
        ),
    ]
