# Generated by Django 3.0.5 on 2021-03-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0062_auto_20210309_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='time_increment',
            field=models.IntegerField(default=15),
        ),
    ]
