# Generated by Django 3.0.5 on 2021-03-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0063_auto_20210309_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='forecasting',
            field=models.BooleanField(default=False),
        ),
    ]
