# Generated by Django 3.0.5 on 2021-03-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0065_auto_20210314_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': [('manage_departments', 'Manage Departments'), ('manage_positions', 'Manage Positions'), ('manage_employees', 'Manage Employees'), ('manage_shifts', 'Manage Shifts'), ('view_employee_uuid', 'View Employee UUIDs'), ('set_employee_wage', 'Set Employee Wage'), ('view_employee_wage', 'View Employee Wage'), ('approve_shifts', 'Approve Shifts'), ('create_forecasts', 'Create Forecasts'), ('view_forecasts', 'View Forecasts'), ('view_availabilities', 'View Availabilities'), ('manage_unavailabilities', 'Manage Unavailabilities'), ('view_shift_stats', 'View Shift Stats'), ('view_wage_stats', 'View Wage Stats')]},
        ),
    ]
