# Generated by Django 3.0.5 on 2021-04-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0068_auto_20210424_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
    ]
