# Generated by Django 3.0.5 on 2021-04-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0070_historicalemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalemployee',
            name='business',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='business',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='business',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDepartment',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
        migrations.DeleteModel(
            name='HistoricalPosition',
        ),
        migrations.DeleteModel(
            name='HistoricalShift',
        ),
        migrations.DeleteModel(
            name='HistoricalSite',
        ),
    ]
