# Generated by Django 3.0.5 on 2021-05-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0072_historicaldepartment_historicalemployee_historicalposition_historicalshift_historicalsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='wage_type',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='wage_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wage_type', models.CharField(choices=[('H', 'Hourly'), ('S', 'Salary'), ('N', 'None')], default='N', max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage', to='rota_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='rota_app.Employee')),
            ],
        ),
    ]
