# Generated by Django 3.0.5 on 2021-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0073_auto_20210504_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
