# Generated by Django 3.0.5 on 2021-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0074_auto_20210504_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestatus',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
