# Generated by Django 3.0.5 on 2021-07-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0077_auto_20210606_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
