# Generated by Django 3.0.5 on 2021-06-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0077_auto_20210606_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_types', models.CharField(choices=[('Holiday', 'Holiday'), ('Unavailable', 'Unavailable')], default='Holiday', max_length=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_availability', to='rota_app.Employee')),
            ],
        ),
    ]
