# Generated by Django 3.0.5 on 2021-06-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0078_newavailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newavailability',
            old_name='availability_types',
            new_name='availability_type',
        ),
    ]
