# Generated by Django 3.0.5 on 2021-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0078_auto_20210709_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
