# Generated by Django 3.0.5 on 2021-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0079_auto_20210617_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='newavailability',
            name='stage',
            field=models.CharField(choices=[('Unmarked', 'Unmarked'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Unmarked', max_length=14),
        ),
    ]
