# Generated by Django 3.0.5 on 2021-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0081_auto_20210802_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='approved',
        ),
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=11),
        ),
    ]
