# Generated by Django 3.0.5 on 2021-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0082_auto_20210805_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
