# Generated by Django 3.0.5 on 2021-08-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0084_auto_20210809_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': [('manage_departments', 'Manage Departments'), ('manage_positions', 'Manage Positions'), ('manage_employees', 'Manage Employees'), ('manage_shifts', 'Manage Shifts'), ('manage_wages', 'Manage Employee Wages'), ('create_forecasts', 'Create Forecasts'), ('view_forecasts', 'View Forecasts'), ('manage_availabilities', 'Manage Availabilities'), ('view_stats', 'View Stats'), ('approve_shifts', 'Approve Shifts')]},
        ),
    ]
