# Generated by Django 3.0.5 on 2021-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0085_auto_20210809_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
