# Generated by Django 3.0.5 on 2021-08-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0086_auto_20210812_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshift',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='wage_type',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='wage_type',
        ),
    ]
