# Generated by Django 3.0.5 on 2021-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0087_auto_20210812_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='amount',
            new_name='actual',
        ),
        migrations.AddField(
            model_name='forecast',
            name='predicted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
