# Generated by Django 3.0.5 on 2021-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0088_auto_20210817_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='predicted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
