# Generated by Django 3.0.5 on 2021-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0089_auto_20210817_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
