# Generated by Django 3.0.5 on 2021-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0090_auto_20210819_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='clock_out',
            field=models.TimeField(null=True),
        ),
    ]
