# Generated by Django 3.0.5 on 2022-01-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0094_auto_20220104_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclock',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeclock_department', to='rota_app.Department'),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_timeclock', to='rota_app.Employee'),
        ),
    ]
