# Generated by Django 3.0.5 on 2022-01-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0095_auto_20220114_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='shift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota_app.Shift'),
        ),
    ]
