# Generated by Django 3.0.5 on 2022-01-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0096_auto_20220114_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclock',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
