# Generated by Django 3.0.5 on 2022-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0099_employeepermissions_permissiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontype',
            name='code_name',
            field=models.CharField(default='TEst', max_length=30),
            preserve_default=False,
        ),
    ]
