# Generated by Django 3.0.5 on 2022-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0100_permissiontype_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='employee_permissions', to='rota_app.PermissionType'),
        ),
        migrations.DeleteModel(
            name='EmployeePermissions',
        ),
    ]
