# Generated by Django 3.0.5 on 2022-01-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0101_auto_20220122_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='site',
            name='admins',
        ),
    ]
