# Generated by Django 3.0.5 on 2022-03-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0102_auto_20220124_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalshift',
            old_name='open_shift',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='open_shift',
            new_name='open',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='published',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='published',
        ),
    ]
