# Generated by Django 3.0.5 on 2022-03-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0103_auto_20220302_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshift',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='absence_info',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='absence_info',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='seen',
        ),
    ]
