# Generated by Django 3.2 on 2022-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0104_auto_20220303_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldepartment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical department', 'verbose_name_plural': 'historical departments'},
        ),
        migrations.AlterModelOptions(
            name='historicalemployee',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical employee', 'verbose_name_plural': 'historical employees'},
        ),
        migrations.AlterModelOptions(
            name='historicalposition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical position', 'verbose_name_plural': 'historical positions'},
        ),
        migrations.AlterModelOptions(
            name='historicalshift',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical shift', 'verbose_name_plural': 'historical shifts'},
        ),
        migrations.AlterModelOptions(
            name='historicalsite',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical site', 'verbose_name_plural': 'historical sites'},
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalshift',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
