# Generated by Django 3.2 on 2022-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0106_alter_business_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
