# Generated by Django 3.2 on 2022-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0107_business_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
    ]
