# Generated by Django 3.2 on 2022-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0109_business_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
