# Generated by Django 3.2 on 2022-06-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0110_auto_20220528_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_been_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='has_been_invited',
            field=models.BooleanField(default=False),
        ),
    ]
