# Generated by Django 3.2 on 2022-06-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0111_auto_20220602_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='positions',
        ),
        migrations.AddField(
            model_name='historicalshift',
            name='position',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rota_app.position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_positions', to='rota_app.position'),
        ),
    ]
