# Generated by Django 3.2 on 2022-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0112_auto_20220602_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='site',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_site', to='rota_app.Site'),
        ),
    ]
