# Generated by Django 3.2 on 2022-06-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0113_employee_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshift',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rota_app.site'),
        ),
        migrations.AddField(
            model_name='shift',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_site', to='rota_app.site'),
        ),
    ]
