# Generated by Django 3.2 on 2022-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0115_timeclock_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='show_welcome',
            field=models.BooleanField(default=True),
        ),
    ]
