# Generated by Django 3.2 on 2022-06-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0116_business_show_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_created_employee', models.BooleanField(default=False)),
                ('has_created_shift', models.BooleanField(default=False)),
                ('has_invited_employee', models.BooleanField(default=False)),
                ('has_created_position', models.BooleanField(default=False)),
                ('has_created_department', models.BooleanField(default=False)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rota_app.business')),
            ],
        ),
    ]
