# Generated by Django 3.2 on 2022-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0118_auto_20220619_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='has_created_account',
            field=models.BooleanField(default=False),
        ),
    ]
