# Generated by Django 3.2 on 2022-07-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota_app', '0119_checklist_has_created_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='has_published_shift',
            field=models.BooleanField(default=False),
        ),
    ]
