export const GET_ALL_SHIFTS = "GET_ALL_SHIFTS";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const GET_POSITIONS = "GET_POSITIONS";
export const GET_ALL_POSITIONS = "GET_ALL_POSITIONS";
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_POSITION = "ADD_POSITION";
export const ADD_SHIFT = "ADD_SHIFT";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_WIDTH = "SET_WIDTH";
export const GET_SHIFTS_BY_ID = "GET_SHIFTS_BY_ID";
export const SHIFTS_LOADING = "SHIFTS_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const DELETE_SHIFT = "DELETE_SHIFT";
export const DELETE_POSITION = "DELETE_POSITION";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const GET_POPULAR_TIMES = "GET_POPULAR_TIMES";
export const RESET_DEPARTMENT = "RESET_DEPARTMENT";
export const UPDATE_SHIFT = "UPDATE_SHIFT";
export const PUBLISHED_SHIFTS = "PUBLISHED_SHIFTS";
export const SWAP_SHIFTS = "SWAP_SHIFTS";
export const GET_SWAP_REQUESTS = "GET_SWAP_REQUESTS";
export const UUID_SUCCESS = "UUID_SUCCESS";
export const UUID_RESET = "UUID_RESET";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_POSITION = "UPDATE_POSITION";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";

export const GET_SITES = "GET_SITES";
export const ADD_SITE = "ADD_SITE";
export const UPDATE_SITE = "UPDATE_SITE";
export const DELETE_SITE = "DELETE_SITE";
export const SET_SITE = "SET_SITE";

export const GET_AVAILABILITY = "GET_AVAILABILITY";
export const ADD_AVAILABILITY = "ADD_AVAILABILITY";
export const UPDATE_AVAILABILITY = "UPDATE_AVAILABILITY";
export const DELETE_AVAILABILITY = "DELETE_AVAILABILITY";
export const GET_HOLIDAYS = "GET_HOLIDAYS";
export const SEND_CHARGE = "SEND_CHARGE";

export const SET_BUSINESS = "SET_BUSINESS";
export const CHARGE_COMPLETE = "CHARGE_COMPLETE";

export const LOAD_START = "LOAD_START";
export const LOAD_FINISH = "LOAD_FINISH";
export const SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED";
export const GET_SUBSCRIPTION = "GET_SUBSCRIPTION";

export const SEND_MESSAGE = "SEND_MESSAGE";

export const RESET_LOADING = "RESET_LOADING";